// mod day_01;
// mod day_02;
// mod day_03;
// mod day_04;
// mod day_09;
// mod day_10;
//mod day_11;
mod day_14;

fn main() {
    // println!("Day 1 : First star result");
    // day_01::first_star::main();
    // println!("Day 1 : Second star result");
    // day_01::second_star::main();
    // println!("Day 2 : First star result");
    // day_02::first_star::main();
    // println!("Day 2 : Second star result");
    // day_02::second_star::main();
    //println!("Day 3 : First star result");
    //day_03::first_star::main();
    //println!("Day 3 : Second star result");
    //day_03::second_star::main();
    //println!("Day 4 : First star result");
    //day_04::first_star::main();
    //println!("Day 9 : First star result");
    //day_09::first_star::main();
    //println!("Day 9 : Second star result");
    //day_09::second_star::main();
    //println!("Day 10 : First star result");
    //day_10::first_star::main();
    //println!("Day 10 : Second star result");
    //day_10::second_star::main();
    //println!("Day 11 : First star result");
    //day_11::first_star::main();
    //println!("Day 11 : Second star result");
    //day_11::second_star::main();
    //println!("Day 14 : First star result");
    //day_14::first_star::main();
    println!("Day 14 : Second star result");
    day_14::second_star::main();
}